name: reviewapp
description: A Review application built with Flutter framework.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:  
  flutter:  
    sdk: flutter  
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  http: ^0.13.6

dev_dependencies:  
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0  
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:  
    - assets/cinepresa.gif
    - assets/icon.png
    - assets/Giovanni.png
